-- GENERATED by tools/recolor.py -- do not edit by hand.
-- Maps vanilla express sprites to their recolored armored counterparts.

return
{
  ["__base__/graphics/entity/express-transport-belt/express-transport-belt.png"] =
    "__armored-belts__/graphics/entity/armored-transport-belt/armored-transport-belt.png",
  ["__base__/graphics/entity/express-transport-belt/remnants/express-transport-belt-remnants.png"] =
    "__armored-belts__/graphics/entity/armored-transport-belt/remnants/armored-transport-belt-remnants.png",
  ["__base__/graphics/entity/express-underground-belt/express-underground-belt-structure.png"] =
    "__armored-belts__/graphics/entity/armored-underground-belt/armored-underground-belt-structure.png",
  ["__base__/graphics/entity/express-underground-belt/express-underground-belt-structure-back-patch.png"] =
    "__armored-belts__/graphics/entity/armored-underground-belt/armored-underground-belt-structure-back-patch.png",
  ["__base__/graphics/entity/express-underground-belt/express-underground-belt-structure-front-patch.png"] =
    "__armored-belts__/graphics/entity/armored-underground-belt/armored-underground-belt-structure-front-patch.png",
  ["__base__/graphics/entity/express-underground-belt/remnants/express-underground-belt-remnants.png"] =
    "__armored-belts__/graphics/entity/armored-underground-belt/remnants/armored-underground-belt-remnants.png",
  ["__base__/graphics/entity/express-splitter/express-splitter-north.png"] =
    "__armored-belts__/graphics/entity/armored-splitter/armored-splitter-north.png",
  ["__base__/graphics/entity/express-splitter/express-splitter-south.png"] =
    "__armored-belts__/graphics/entity/armored-splitter/armored-splitter-south.png",
  ["__base__/graphics/entity/express-splitter/express-splitter-east.png"] =
    "__armored-belts__/graphics/entity/armored-splitter/armored-splitter-east.png",
  ["__base__/graphics/entity/express-splitter/express-splitter-west.png"] =
    "__armored-belts__/graphics/entity/armored-splitter/armored-splitter-west.png",
  ["__base__/graphics/entity/express-splitter/express-splitter-east-top_patch.png"] =
    "__armored-belts__/graphics/entity/armored-splitter/armored-splitter-east-top_patch.png",
  ["__base__/graphics/entity/express-splitter/express-splitter-west-top_patch.png"] =
    "__armored-belts__/graphics/entity/armored-splitter/armored-splitter-west-top_patch.png",
  ["__base__/graphics/entity/express-splitter/remnants/express-splitter-remnants.png"] =
    "__armored-belts__/graphics/entity/armored-splitter/remnants/armored-splitter-remnants.png",
  ["__base__/graphics/icons/express-transport-belt.png"] =
    "__armored-belts__/graphics/icons/armored-transport-belt.png",
  ["__base__/graphics/icons/express-underground-belt.png"] =
    "__armored-belts__/graphics/icons/armored-underground-belt.png",
  ["__base__/graphics/icons/express-splitter.png"] =
    "__armored-belts__/graphics/icons/armored-splitter.png",
  ["__base__/graphics/technology/logistics-3.png"] =
    "__armored-belts__/graphics/technology/armored-belts.png",
}
