"""
Generates the armored belt graphics from the vanilla express belt sprites.

The express sprites are already mostly gray metal; what makes them read as blue
is a cyan accent (hue ~180). So this does NOT flatten the art to grayscale --
it strips the chroma and keeps every bit of luminance, which is where the tread
detail and the sense of motion live.

Re-run after tweaking the constants below:
    python tools/recolor.py
"""

import os
import numpy as np
from PIL import Image

# --- tuning knobs ------------------------------------------------------------
DESAT   = 0.92                    # 1.0 = fully neutral gray
CONTRAST= 0.12                    # smoothstep blend, keeps plating crisp
LIFT    = 1.10                    # midtone gamma lift; bare metal reads brighter
TINT    = (0.965, 0.978, 1.000)   # faint cool cast -> steel/titanium, not warm
# -----------------------------------------------------------------------------

BASE = r"C:\Program Files (x86)\Steam\steamapps\common\Factorio\data\base\graphics"
MOD  = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "graphics")

SOURCES = [
    r"entity\express-transport-belt\express-transport-belt.png",
    r"entity\express-transport-belt\remnants\express-transport-belt-remnants.png",
    r"entity\express-underground-belt\express-underground-belt-structure.png",
    r"entity\express-underground-belt\express-underground-belt-structure-back-patch.png",
    r"entity\express-underground-belt\express-underground-belt-structure-front-patch.png",
    r"entity\express-underground-belt\remnants\express-underground-belt-remnants.png",
    r"entity\express-splitter\express-splitter-north.png",
    r"entity\express-splitter\express-splitter-south.png",
    r"entity\express-splitter\express-splitter-east.png",
    r"entity\express-splitter\express-splitter-west.png",
    r"entity\express-splitter\express-splitter-east-top_patch.png",
    r"entity\express-splitter\express-splitter-west-top_patch.png",
    r"entity\express-splitter\remnants\express-splitter-remnants.png",
    r"icons\express-transport-belt.png",
    r"icons\express-underground-belt.png",
    r"icons\express-splitter.png",
    (r"technology\logistics-3.png", r"technology\armored-belts.png"),
]


def recolor(arr):
    rgb = arr[..., :3].astype(np.float32) / 255.0

    # HSL lightness, not luma: a saturated cyan keeps its apparent brightness
    # instead of collapsing to a dark gray the way 0.21/0.72/0.07 would.
    lightness = (rgb.max(-1, keepdims=True) + rgb.min(-1, keepdims=True)) * 0.5

    out = rgb * (1.0 - DESAT) + lightness * DESAT
    out = np.clip(out, 0.0, 1.0)

    smooth = out * out * (3.0 - 2.0 * out)
    out = out * (1.0 - CONTRAST) + smooth * CONTRAST

    out = np.power(out, 1.0 / LIFT)
    out = out * np.array(TINT, dtype=np.float32)

    result = arr.copy()
    result[..., :3] = np.clip(out * 255.0 + 0.5, 0, 255).astype(np.uint8)
    return result


mapping = []
for entry in SOURCES:
    rel, dst_rel = entry if isinstance(entry, tuple) else (entry, entry.replace("express", "armored"))
    src = os.path.join(BASE, rel)
    dst = os.path.join(MOD, dst_rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)

    im = Image.open(src).convert("RGBA")
    Image.fromarray(recolor(np.array(im))).save(dst, optimize=True)

    to_posix = lambda p: p.replace("\\", "/")
    mapping.append((f"__base__/graphics/{to_posix(rel)}",
                    f"__armored-belts__/graphics/{to_posix(dst_rel)}"))
    print(f"  {os.path.basename(dst_rel):<52} {im.size[0]}x{im.size[1]}")

# Written from the files actually produced, so the Lua can never point at a
# sprite that does not exist on disk.
lua = os.path.join(os.path.dirname(MOD), "prototypes", "graphics-map.lua")
with open(lua, "w", encoding="utf-8") as f:
    f.write("-- GENERATED by tools/recolor.py -- do not edit by hand.\n")
    f.write("-- Maps vanilla express sprites to their recolored armored counterparts.\n\n")
    f.write("return\n{\n")
    for a, b in mapping:
        f.write(f'  ["{a}"] =\n    "{b}",\n')
    f.write("}\n")

print(f"\n{len(mapping)} sprites -> {MOD}")
print(f"map -> {lua}")
